language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

sudo: required

addons:
  apt:
    sources:
      sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - git
      - autoconf
      - automake
      - pkg-config
      - libtool
      - make
      - tcl
      - libpcre3-dev
      - libcap-dev
      - flex
      - hwloc
      - lua5.2
      - libncurses-dev
      - curl

# sets up pylint
before_install: sudo add-apt-repository -y ppa:jonathonf/gcc-7.1 && sudo apt-get update && sudo apt-get install -y gcc-7 g++-7 python -m pip install -y pylint

# Install step (should handle dependencies)
install: python -m pip install .

# Build step (Checks pylint score as well)
script: ./test.sh
