language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

sudo: required

addons:
  apt:
    packages:
      - git
      - autoconf
      - automake
      - software-properties-common
      - pkg-config
      - libtool
      - make
      - tcl
      - libpcre3-dev
      - libcap-dev
      - flex
      - hwloc
      - lua5.2
      - libncurses-dev
      - curl

# sets up pylint
before_install: 'wget http://ftp.ports.debian.org/debian-ports//pool-x32/main/g/gcc-defaults/gcc_7.3.0-3_x32.deb && sudo dpkg -i ./*.deb && python -m pip install -y pylint'

# Install step (should handle dependencies)
install: python -m pip install .

# Build step (Checks pylint score as well)
script: ./test.sh
